name 'rxp-rabbit-server'
maintainer 'I&O'
maintainer_email 'sysadministrators@globalpay.com'
license 'all_rights'
description 'Installs/Configures X'
long_description 'Installs/Configures X'
version '1.0.0'
issues_url 'http://bitbucket.rxpdev.com:7990/projects/CHEF/repos/rxp-rabbit-server/browse'
source_url 'http://bitbucket.rxpdev.com:7990/projects/CHEF/repos/rxp-rabbit-server/browse'
depends 'rabbitmq', '~> 5.6.1'
